name: Production Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Билд и запуск
        run: docker compose up --build -d
